### ISSUE TITLE
Too old version of python opencv

### ISSUE THREAD

**Issue by quirinklr** [danielsyahputra/yolov9-onnx#3]
Hello,

you need to run following commands in order to make it work. OpenCV is outdated and throws following error:
_cv2.error: OpenCV(4.9.0) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:1272: error: (-2:Unspecified error)_

Solution for that are following commands:

```
pip uninstall opencv-python-headless -y 
pip install opencv-python --upgrade
```

**Comment by danielsyahputra** [comment]
Noted. Thank you for your information.
