### ISSUE TITLE
ONNX model type

### ISSUE THREAD

**Issue by CompanionG** [danielsyahputra/yolov9-onnx#4]
Hello , i see you are using yolov9-c.onnx .
I use yolov9-s.pt
`python export.py --include onnx`
and it successfully export yolov9-s.onnx. through netron tool i can see the difference between -c.onnx and -s.onnx.
My question is the script whether adapt to -s.onnx.I can see the input and output shape is same.

yolov9s
![image](https://github.com/danielsyahputra/yolov9-onnx/assets/89848374/d3b7cf27-824e-43f9-8eb9-8875d4bab8f4)
yolov9c
![image](https://github.com/danielsyahputra/yolov9-onnx/assets/89848374/453da38e-2a00-4721-bf43-f4b034989e08)

**Comment by danielsyahputra** [comment]
Yes, the script is also can be adapt to -s onnx version.

**Comment by CompanionG** [comment]
@danielsyahputra  I need to process multi images , every time i inference i must init onnx session. Is there any ways to load model just once.
